version: '3'

services:
#  user:
#    image: 'user-project:latest'
#    build:
#      context: ./User/
#    depends_on:
#      - user-postgresql
#    ports:
#      - '8080:8080'
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgresql:5432/user_db
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=very-secure-password

  user-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 15432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=user_db

#  order:
#    image: 'order-project:latest'
#    build:
#      context: ./Order
#    ports:
#      - '8081:8080'
#    depends_on:
#      - order-postgresql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-postgresql:5432/order_db
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=very-secure-password

  order-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 25432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=order_db

#  product:
#    image: 'product-project:latest'
#    build:
#      context: ./Product
#    ports:
#      - '8082:8080'
#    depends_on:
#      - product-postgresql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-postgresql:5432/product_db
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=very-secure-password

  shopping-cart-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 35432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=shopping_cart_db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka-server-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper

#  nginx:
#    image: nginx:1.25.1
#    restart: always
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
#    depends_on:
#      - user
#      - order
#      - product
#    ports:
#      - '8080:8080'
